
modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
[[mods]]
modId="extrakeybindsforge"
version="1.2-1.19.x"
displayName="Extra Keybinds Forge"
authors="fireheart3911"

description='''
A mod to add some more keybinds for easier origin creation.
'''
[[dependencies.extrakeybindsforge]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extrakeybindsforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
